import { fileURLToPath, URL } from "node:url";

import vue from "@vitejs/plugin-vue";
import { defineConfig } from "vite";
import Components from "unplugin-vue-components/vite";
import { ElementPlusResolver } from "unplugin-vue-components/resolvers";
import * as elementPlusIcons from "@element-plus/icons-vue";

/**
 * Icons are written straight into the templates (`<Plus />`, `<Calendar />`) and used to work
 * because main.ts registered all ~290 of them globally. This resolver imports only the ones a
 * template actually mentions; the membership check keeps a typo in a tag name an error instead
 * of a silent broken import.
 */
const iconResolver = {
    type: "component" as const,
    resolve: (name: string) => (name in elementPlusIcons ? { name, from: "@element-plus/icons-vue" } : undefined),
};

export default defineConfig({
    /**
     * Relative base makes the production build work no matter which subfolder
     * it is hosted from (GitHub Pages project pages, a local `dist` preview, etc.).
     */
    base: "./",
    plugins: [
        vue(),
        /**
         * Element Plus on demand: only the components actually used in the templates end up in
         * the bundle, together with their styles. Registering the whole library globally in
         * main.ts used to pull in all ~80 components and every stylesheet.
         * `src/components.d.ts` is generated by this plugin and is committed so that the editor
         * resolves the auto-imported components without a dev server running. The build does not
         * depend on it today (`strictTemplates` is off, so vue-tsc lets unknown tags pass), but it
         * would the moment that is turned on.
         */
        Components({
            dts: "src/components.d.ts",
            resolvers: [ElementPlusResolver(), iconResolver],
            // Only Element Plus is auto-imported; our own components stay explicit imports.
            dirs: [],
        }),
    ],
    resolve: {
        alias: {
            "@": fileURLToPath(new URL("./src", import.meta.url)),
        },
    },
    server: {
        port: 5173,
    },
});
