/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArrowLeft: typeof import('@element-plus/icons-vue')['ArrowLeft']
    Calendar: typeof import('@element-plus/icons-vue')['Calendar']
    Check: typeof import('@element-plus/icons-vue')['Check']
    Close: typeof import('@element-plus/icons-vue')['Close']
    CopyDocument: typeof import('@element-plus/icons-vue')['CopyDocument']
    DArrowLeft: typeof import('@element-plus/icons-vue')['DArrowLeft']
    DArrowRight: typeof import('@element-plus/icons-vue')['DArrowRight']
    Delete: typeof import('@element-plus/icons-vue')['Delete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Menu: typeof import('@element-plus/icons-vue')['Menu']
    Moon: typeof import('@element-plus/icons-vue')['Moon']
    MoreFilled: typeof import('@element-plus/icons-vue')['MoreFilled']
    Plus: typeof import('@element-plus/icons-vue')['Plus']
    RefreshLeft: typeof import('@element-plus/icons-vue')['RefreshLeft']
    RefreshRight: typeof import('@element-plus/icons-vue')['RefreshRight']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('@element-plus/icons-vue')['Setting']
    Sunny: typeof import('@element-plus/icons-vue')['Sunny']
  }
}
